name: Generate Snake Animation

on:
  schedule:
    - cron: "0 12 * * *" # Runs every day at noon
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: thuggys
          svg_out_path: dist/github-contribution-grid-snake-purple.svg
          snake_color: 'purple'

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
